name: React Native CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Install & Build Expo App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Run tests (if available)
        run: npm test

      - name: Expo build check
        run: npx expo export --dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t lifestation .

      - name: Run Docker container
        run: |
          docker run -d \
            -p 19000:19000 \
            -p 19001:19001 \
            -p 19002:19002 \
            -p 8081:8081 \
            --name lifestation-container lifestation

      - name: Check container logs
        run: docker logs lifestation-container

      - name: Cleanup Docker resources
        if: always()
        run: |
          docker stop lifestation-container || true
          docker rm lifestation-container || true
          docker rmi lifestation || true

        