name: React Native CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Install & Build Expo App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install
        working-directory: LifeStation

      - name: TypeScript check
        run: npx tsc --noEmit
        working-directory: LifeStation

      - name: Run tests (if available)
        run: npm test
        working-directory: LifeStation

      - name: Expo build check
        run: npx expo export --dev
        working-directory: LifeStation

        